export const profiles =[
    {
        id:'0001',
        userName:'reaangela',
        password:'Qwertyuiop45',
        userType:'Student',
        name:{
            firstName:'Rea Angela',
            lastName:'Galleros',
        },
        course:'BSIT',
        yearSection:'3B',
    },
    {
        id:'0002',
        userName:'anaphilyang',
        password:'ohhmay',
        userType:'Student',
        name:{
            firstName:'Anaphil',
            lastName:'Jaojao',
        },
        course:'Accountancy',
        yearSection:'1A',
    },
    {
        id:'0003',
        userName:'Mayang',
        password:'ncjshfslav',
        userType:'Student',
        name:{
            firstName:'Maia',
            lastName:'Acorda',
        },
        course:'BSOA',
        yearSection:'2B',
    },
    {
        id:'0004',
        userName:'_eplixx',
        password:'hisidwnnisijp',
        userType:'Teacher',
        name:{
            firstName:'Karl',
            lastName:'Loquias',
        },
        course:'BSIT',
        yearSection:'3B',
    },
    {
        id:'0005',
        userName:'opaaww',
        password:'nohate',
        userType:'Teacher',
        name:{
            firstName:'Mark Antony',
            lastName:'Jandugan',
        },
        course:'BSMT',
        yearSection:'2B',
    },
    {
        id:'0006',
        userName:'iamtheking',
        password:'sukunalangmalakas',
        userType:'Student',
        name:{
            firstName:'Nikko Brylle',
            lastName:'Alturas',
        },
        course:'BSIT',
        yearSection:'3B',
    },
    {
        id:'0007',
        userName:'marjkyut',
        password:'stoneheariron',
        userType:'Student',
        name:{
            firstName:'Marjoleine',
            lastName:'Egama',
        },
        course:'BSIT',
        yearSection:'3B',
    },
    {
        id:'0008',
        userName:'m_avery',
        password:'businessisdakey',
        userType:'Student',
        name:{
            firstName:'Mary Avery',
            lastName:'Butawan',
        },
        course:'BSIT',
        yearSection:'3B',
    
    
    },
]